# Generated by Django 3.2b1 on 2021-03-10 14:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import module.common


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bbs_questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', max_length=50, validators=[django.core.validators.MaxLengthValidator(50), module.common.NgWord], verbose_name='名前')),
                ('url', models.URLField(blank=True, default='', max_length=250, validators=[django.core.validators.MaxLengthValidator(250)], verbose_name='URL')),
                ('body', models.TextField(default='', validators=[module.common.NgWord], verbose_name='本文')),
                ('ip', models.CharField(db_index=True, default='', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bbs_questions.question', verbose_name='質問ID')),
            ],
            options={
                'verbose_name': '回答',
                'db_table': 'bbs_answers',
            },
        ),
    ]
