# Generated by Django 3.2b1 on 2021-03-10 14:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import module.common


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bbs_langtypes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150, unique=True, validators=[django.core.validators.MaxLengthValidator(150), module.common.NgWord], verbose_name='タイトル')),
                ('resolved', models.BooleanField(default=False, verbose_name='解決')),
                ('pv', models.IntegerField(default=0, verbose_name='PV')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField()),
                ('lang_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bbs_langtypes.langtype', verbose_name='カテゴリID')),
            ],
            options={
                'verbose_name': '質問',
                'db_table': 'bbs_questions',
            },
        ),
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matome', models.TextField(default='', verbose_name='本文')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bbs_questions.question', verbose_name='質問ID')),
            ],
            options={
                'verbose_name': '検索用',
                'db_table': 'bbs_bodies',
            },
        ),
    ]
