# Generated by Django 3.2b1 on 2021-03-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yyyy', models.IntegerField(db_index=True, verbose_name='年')),
                ('mm', models.IntegerField(db_index=True, verbose_name='月')),
                ('dd', models.IntegerField(db_index=True, verbose_name='日')),
                ('pv', models.IntegerField(verbose_name='PV')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'アクセス',
                'db_table': 'bbs_accesses',
            },
        ),
    ]
