# Generated by Django 3.2b1 on 2021-03-04 03:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LangType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, unique=True, validators=[django.core.validators.MaxLengthValidator(50)], verbose_name='名前')),
                ('keywords', models.CharField(default='', max_length=100, validators=[django.core.validators.MaxLengthValidator(100)], verbose_name='キーワード')),
                ('description', models.TextField(blank=True, default='', max_length=512, validators=[django.core.validators.MaxLengthValidator(512)], verbose_name='説明')),
                ('sort', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='ソート')),
                ('show', models.BooleanField(default=True, verbose_name='表示')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'カテゴリ',
                'db_table': 'bbs_lang_types',
            },
        ),
    ]
